---
- name: Guess the group from lyrics
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    lyrics_path: "./"
    keyword_map:
      destinys_child: ["survivor", "say my name", "cater to you"]
      spice_girls: ["wannabe", "spice up", "goodbye"]
      nsync: ["bye bye bye", "tearing up", "it's gonna be me"]
      kiss: ["rock and roll", "detroit", "beth"]

  tasks:
    - name: Find all song lyrics
      find:
        paths: "{{ lyrics_path }}"
        patterns: "*.txt"
        recurse: yes
      register: lyric_files

    - name: Read and analyze lyrics
      command: cat "{{ item.path }}"
      loop: "{{ lyric_files.files }}"
      register: lyric_contents

    - name: Detect and print group
      vars:
        detected_group: >-
          {% set match = 'Unknown' %}
          {% for group, keywords in keyword_map.items() %}
            {% for keyword in keywords %}
              {% if keyword in item.stdout | lower %}
                {% set match = group %}
                {% break %}
              {% endif %}
            {% endfor %}
            {% if match != 'Unknown' %}
              {% break %}
            {% endif %}
          {% endfor %}
          {{ match }}
      loop: "{{ lyric_contents.results }}"
      loop_control:
        label: "{{ item.item.path }}"
      debug:
        msg: "The song '{{ item.item.path }}' likely belongs to '{{ detected_group }}'"
